server:
 port: 10004

eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:10003/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10

spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:joaoevangelista/librarian-config.git


security:
  sessions: NEVER
  user:
    password: nessa
