server:
 port: 10010

eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:10003/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10


security:
  sessions: NEVER
  user:
    password: nessa



