server:
 port: 10003

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:10003/eureka/
  server:
    enableSelfPreservation: true
    waitTimeInMsWhenSyncEmpty: 0
