server:
  port: 8093

eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:10003/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10

spring:
  oauth2:
      client:
        clientId: cae4925a4ce2feb76ec8
        clientSecret: 41df89b5d95976f0028045889e2c2596fbd6b417
        accessTokenUri: https://github.com/login/oauth/access_token
        userAuthorizationUri: https://github.com/login/oauth/authorize
        clientAuthenticationScheme: form
      resource:
        userInfoUri: https://api.github.com/user
        preferTokenInfo: false

security:
  user:
    password: none

logging:
  level:
    org:
      springframework:
        web: INFO
    curly: TRACE
    com:
      netflix:
        discovery: OFF
  file: application.log

